### ISSUE TITLE
[1.20.1] | Could not load 'plugins\RFriend-1.0.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by TeQTabanca** [Weesli/RFriend#1]
- I saw that your plugin is useful, but it does not work in version 1.20.1.

- I have a question. Can the /friend message command send a message to a player who is not in the game?
If this feature does not exist in this command, it would be nice if it could be added.

- I have 2 feature requests. Several placeholders can be added thanks to the PlaceholderAPI plugin.

1 - %rfriend_online_friends% (It will show the number of online players)
2 - %rfriend_offline_friends% (It will show the number of offline players.)
3 - %rfriend_total_friends% ( It will show the total friends list.)
4 - %rfriend_invited_friends% (This will show the number of invited friends.)

- /friend invites command can be added. It will show the list of players we are trying to add. (It may be better to open it as GUI. Additionally, a message needs to be added to show when we sent the friend invitation.)

```java
[19:49:29] [Server thread/ERROR]: Could not load 'plugins\RFriend-1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/weesli/rozsLib/configuration/YamlFileBuilder
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:435) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/weesli/rozsLib/configuration/YamlFileBuilder
        at net.weesli.shared.RFriend.<init>(RFriend.java:27) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
        at java.lang.Class.newInstance(Class.java:725) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.weesli.rozsLib.configuration.YamlFileBuilder
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.weesli.shared.RFriend.<init>(RFriend.java:27) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
        at java.lang.Class.newInstance(Class.java:725) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 7 more
[19:49:29] [Server thread/INFO]: [RozsLib] Loading RozsLib v2.0.0
```

**Comment by Weesli** [comment]
Hello,

Troubleshooting will be done for the given error. However, the invitations sent regarding the invitation list you requested are not stored in the files. In other words, these invitations are deleted when you turn off the server or at certain time intervals. therefore, feature requests related to the invitations sent will not be made at this time.

**Comment by TeQTabanca** [comment]
> Hello,
> 
> Troubleshooting will be done for the given error. However, the invitations sent regarding the invitation list you requested are not stored in the files. In other words, these invitations are deleted when you turn off the server or at certain time intervals. therefore, feature requests related to the invitations sent will not be made at this time.

I tested it now, but the player cannot join the server. There are no errors in the server console.

```java
[21:28:26] [Server thread/INFO]: Test lost connection: Disconnected
[21:28:26] [Server thread/INFO]: Test left the game
[21:28:26] [Server thread/WARN]: handleDisconnection() called twice
```

![image](https://github.com/user-attachments/assets/6335e97f-6676-4d07-a4de-37c34319f978)

**Comment by Weesli** [comment]
I don't think this error is related to RFriend. I didn't encounter this error when I tried it on my local server.

**Comment by TeQTabanca** [comment]
> I don't think this error is related to RFriend. I didn't encounter this error when I tried it on my local server.

My mistake, I found out that it was caused by one mod. I tested the plugin...

1 - As a warning message to the friend you want to add, "%player% wants to be friends with you!" can be added as .

2- A warning message can be added when the player logs into the server telling them how many friends are online. "You have %online_friends% friend online on the server!". Lastly, it can also be valid for friend invitations sent. "%total_friend_request% players want to be friends with you!"

3 - It would be nice if sending a message to a friend who is offline could be added.

4- If my status property is empty or I type something, it gives a warning in the console, but the feature works.
```java
[Netty Server IO #1/WARN]: net.minecraft.server.CancelledPacketHandleException
```

5 - After blocking or unfriending a player the gui needs to be updated.

6 - It would be nice if there was a feature to automatically reject friend requests after a certain period of time. The automatic rejection feature should be configurable in the Settings section.

7 - I ran into an issue while testing the ability to block and add a player. If I leave the sign gui blank or type a player's name and press the done button, it gives an error on the console. Finally, even when I type the name of a player who has never played on the server, it gets blocked and I cannot enter the gui of the blocked players. This problem also occurs with the add friend button, but I can enter the friends section again. What I mean is that when the name of a player who has never played on the server is entered, the message "Unknown player" should be given.


The error given in the console when I do not enter the player's name.
```java
[17:48:09] [Netty Server IO #3/WARN]: java.lang.IllegalArgumentException: name cannot be empty
[17:48:09] [Netty Server IO #3/WARN]:   at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[17:48:09] [Netty Server IO #3/WARN]:   at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getOfflinePlayer(CraftServer.java:1672)
[17:48:09] [Netty Server IO #3/WARN]:   at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:1140)
[17:48:09] [Netty Server IO #3/WARN]:   at net.weesli.shared.ui.invtentories.BlocksMenu.lambda$openSign$6(BlocksMenu.java:100)
[17:48:09] [Netty Server IO #3/WARN]:   at net.weesli.shared.signgui.SignGUI.lambda$open$1(SignGUI.java:157)
[17:48:09] [Netty Server IO #3/WARN]:   at net.weesli.shared.signgui.SignGUI.lambda$open$2(SignGUI.java:191)
[17:48:09] [Netty Server IO #3/WARN]:   at net.weesli.shared.signgui.version.Wrapper1_20_R1$1.decode(Wrapper1_20_R1.java:122)
[17:48:09] [Netty Server IO #3/WARN]:   at net.weesli.shared.signgui.version.Wrapper1_20_R1$1.decode(Wrapper1_20_R1.java:105)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[17:48:09] [Netty Server IO #3/WARN]:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:48:09] [Netty Server IO #3/WARN]:   at java.base/java.lang.Thread.run(Thread.java:1583)
```

The error given on the console when I enter the player's name.
```java
[17:50:30] [Netty Server IO #3/WARN]: net.minecraft.server.CancelledPacketHandleException
```

The reason why I cannot enter the gui of blocked players.
```java
[18:00:11] [Server thread/ERROR]: Could not pass event InventoryClickEvent to RozsLib v2.0.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2782) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: The skull profile is missing a name or textures!
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile.validateSkullProfile(CraftPlayerProfile.java:38) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftMetaSkull.setOwnerProfile(CraftMetaSkull.java:244) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.weesli.shared.ui.invtentories.BlocksMenu.openInventory(BlocksMenu.java:62) ~[?:?]
        at net.weesli.shared.ui.UIManager.openInventory(UIManager.java:29) ~[?:?]
        at net.weesli.shared.ui.invtentories.MainMenu.lambda$openInventory$3(MainMenu.java:45) ~[?:?]
        at net.weesli.rozsLib.inventory.lasest.InventoryBuilder.lambda$handleClick$4(InventoryBuilder.java:117) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.weesli.rozsLib.inventory.lasest.InventoryBuilder.handleClick(InventoryBuilder.java:113) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```

8- If I add a player before blocking and then block them, the player I blocked still remains in my friends list and can send messages. What I mean is that if a added player is blocked, the blocked player should be automatically removed from the friends list.

**Comment by Weesli** [comment]
Hello,

I really appreciate your detailed review and comments. 😁

I have gone through the features one by one and you can be sure that I will fix many of them in my free time, I have also gone through the bugs. As for the features, I can say that some of them are not possible for now. However, some of them are possible. That's why I can't add everything written here at the moment.

Thanks again for the information. I will release a bug-fixed version as soon as possible 😅

If there are any other problems or errors, please open a new issue.
